preserve_hierarchy: true

files:
  - source: /InterestingNotch/Localizable.xcstrings
    translation: /InterestingNotch/Localizable.xcstrings
    multilingual: true
    skip_untranslated_strings: true
